import type { Metadata } from "next";
import Footer from "@/components/Self/Footer";
import NavBar from "@/components/Self/NavBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <NavBar />
      {children}
    </div>
  );
}
